language: node_js
node_js:
  - node

dist: trusty

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  # - psql -c travis_ci_test < test_db.pgsql -U postgres

install:
  - npm install --build-from-source

script:
  - npm run test
  # - npm run report-coverage
