language: node_js
node_js:
  - node

dist: trusty

addons:
  postgresql: 9.6

before_script:
  - createdb travis_ci_test -U postgres
  - psql travis_ci_test < test_db.pgsql -U postgres
  # - psql -c 'create database travis_ci_test;' -U postgres

env:
  - PGDATABASE=travis_ci_test PGUSER=postgres

install:
  - npm install --build-from-source

script:
  - npm run test
  - npm run report-coverage

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app:
    # master: my-app-staging
    # develop
    heroku-deploy: teamwork-ke-dev
  run:
    - pg:backups:restore 'https://res.cloudinary.com/doltfsoo1/raw/upload/v1573650022/test_db_dsx1k6.pgsql' $DATABASE_URL
