language: node_js
node_js:
  - node

dist: trusty

addons:
  postgresql: 9.6

before_script:
  # - psql -c 'create user yego with password yego;' -U postgres
  - psql -c "create database team_test;" -U postgres
  - psql team_test < test_db.pgsql -U postgres

install:
  - npm install --build-from-source

script:
  - npm run test
  # - npm run report-coverage
