FORMAT: 1A
HOST: https://teamwork-ke-dev.herokuapp.com/api/v1/

# Teamwork

Teamwork is an **internal social network** for employees of an organization. The goal of this
application is to facilitate more interaction between colleagues and promote team bonding.

# Group Articles

## /articles

### List All Articles [GET]

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": [
                  {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "title": "Favourite programming language?",
                      "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                      "user": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "username": "tommy"
                      },
                      "category": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "name": "software"
                      },
                      "createdAt": "2015-08-05T08:40:51.620Z",
                      "updatedAt": "2015-08-05T08:40:51.620Z"
                  }
              ],
            }

### Create a New Article [POST]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "category": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
              "title": "Favourite programming language?",
              "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
              "userId": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                  "title": "Favourite programming language?",
                  "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                  "user": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "category": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "name": "software",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "data": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "data": "Bad data",
            }

## /articles/{id}

+ Parameters

  + id (string) - ID of the article (uuid/v1)

### Get An Article [GET]

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                  "title": "Favourite programming language?",
                  "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                  "user": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "category": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "name": "software",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              }
            }

+ Response 404 (application/json)

    + Body

            {
                "status": "error",
                "error": "No article by that identifier."
            }

### Update An Article [PATCH]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "title": "Favourite programming language?",
              "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            }

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": [
                  {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "title": "Favourite programming language?",
                      "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                      "user": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "username": "tommy",
                      },
                      "category": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "name": "software",
                      },
                      "createdAt": "2015-08-05T08:40:51.620Z",
                      "updatedAt": "2015-08-05T08:40:51.620Z",
                  }
              ]
            }

+ Response 404 (application/json)

    + Body

            {
              "status": "error",
              "error": "No article by that identifier."
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

### Delete An Article [DELETE]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

+ Response 204 (application/json)

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "data": "Not authorized",
            }

+ Response 404 (application/json)

  + Body

            {
              "status": "error",
              "error": "No article found by that identifier."
            }

## /articles/{id}/comment

### Post a comment [POST]

+ Parameters

  + id (string) - ID of the article (uuid/v1)

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "article": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
              "comment": "Wooow, that was awesome!!",
              "userId": "a4e45td0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "c31de8f0-06c6-11ea-8d1e-d1fcfe25170f",
                  "comment": "Wooow, that was awesome!!",
                  "user": {
                      "id": "a4e45td0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "article": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "title": "Favourite programming language?",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

+ Response 404 (application/json)

  + Body

            {
              "status": "error",
              "error": "No article found by that identifier."
            }

## /articles/{id}/flag

### Post a flag [POST]

+ Parameters

  + id (string) - ID of the article (uuid/v1)

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "article": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
              "feedback": "I found this offensive...",
              "userId": "a4e45td0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "7ca03a10-06c9-11ea-8d1e-d1fcfe25170f",
                  "feedback": "I found this offensive...",
                  "user": {
                      "id": "a4e45td0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "article": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "title": "Favourite programming language?",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

+ Response 404 (application/json)

      + Body

            {
              "status": "error",
              "error": "No article found by that identifier."
            }


# Group Gifs

## /gifs

### List All Gifs [GET]

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": [
                  {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "title": "Favourite programming language?",
                      "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                      "user": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "username": "tommy"
                      },
                      "category": {
                          "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                          "name": "software"
                      },
                      "createdAt": "2015-08-05T08:40:51.620Z",
                      "updatedAt": "2015-08-05T08:40:51.620Z"
                  }
              ],
            }

### Create a New Gif [POST]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "category": "89de8c60-06cc-11ea-8d1e-d1fcfe25170f",
              "title": "Favourite programming language?",
              "image": "an-awesome-bike.gif",
              "userId": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                  "title": "Favourite touring bike",
                  "image": "https://secure_url/awesome.gif",
                  "user": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "category": {
                      "id": "89de8c60-06cc-11ea-8d1e-d1fcfe25170f",
                      "name": "vehicles",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
                "status": "error",
                "data": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "data": "Bad data",
            }

## /gifs/{id}

+ Parameters

  + id (string) - ID of the gif (uuid/v1)

### Get A Gif [GET]

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                  "title": "Favourite touring bike",
                  "image": "https://secure_url/awesome.gif",
                  "user": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "category": {
                      "id": "89de8c60-06cc-11ea-8d1e-d1fcfe25170f",
                      "name": "vehicles",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              }
            }

+ Response 404 (application/json)

  + Body

            {
              "status": "error",
              "error": "No gif by that identifier."
            }

### Update A Gif [PATCH]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
            "title": "The old timer",
            "image": "a-new-old-bike.gif"
            }

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                  "title": "The old timer",
                  "image": "http://secure_url/a-new-old-bike.gif",
                  "user": {
                      "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "category": {
                      "id": "89de8c60-06cc-11ea-8d1e-d1fcfe25170f",
                      "name": "vehicles",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              }
            }

+ Response 401 (application/json)

  + Body

            {
                "status": "error",
                "data": "Not authorized",
            }

+ Response 404 (application/json)

    + Body

            {
              "status": "error",
              "error": "No gif by that identifier."
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

### Delete A Gif [DELETE]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

+ Response 204 (application/json)

+ Response 401 (application/json)

  + Body

            {
                "status": "error",
                "data": "Not authorized",
            }

+ Response 404 (application/json)

    + Body

            {
              "status": "error",
              "error": "No gif by that identifier."
            }

## /gifs/{id}/comment

+ Parameters

  + id (string) - ID of the gif (uuid/v1)

### Post a comment [POST]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "gif": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
              "comment": "That gif is awesome dude!!",
              "userId": "a4e45td0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "0957abd0-06d6-11ea-8d1e-d1fcfe25170f",
                  "comment": "That gif is awesome dude!!",
                  "user": {
                    "id": "a4e45td0-064f-11ea-bda7-0f1cd9030e30",
                    "username": "tommy",
                  },
                  "gif": {
                    "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                    "title": "The old timer",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

+ Response 404 (application/json)

  + Body

            {
              "status": "error",
              "error": "No article found by that identifier."
            }

## /gifs/{id}/flag

### Post a flag [POST]

+ Parameters

  + id (string) - ID of the article (uuid/v1)

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "article": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
              "feedback": "I found this offensive...",
              "userId": "a4e45td0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "5df72f30-06d6-11ea-8d1e-d1fcfe25170f",
                  "feedback": "I found this offensive...",
                  "user": {
                      "id": "a4e45td0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "gif": {
                    "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                    "title": "The old timer",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

+ Response 404 (application/json)

      + Body

            {
              "status": "error",
              "error": "No article found by that identifier."
            }


# Group Auth

## /auth/create-user

### Create User  [POST]
+ Request (application/json)
  + Headers

            Authorization: 'Bearer tfdfhdjfyreu68rehnfdjhfdjkfhcxcxhcjsdjfhd'

  + Body

            {
              "username": "ahm",
              "firstName": "Ahmed",
              "lastName": "Jude",
              "email": "ahmed@mail.com",
              "password": "password",
              "gender": "male",
              "mobile": "079445322",
              "address": "34 Fito",
              "department": "sales",
              "role": "ceo",
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "token": "tfdfhdjfyreu68rehnfdjhfdjkfhcxcxh4545jfhd",
                  "id": "dcc00a10-06e2-11ea-8f0e-9168c8a7677c",
                  "username": "ahm",
                  "firstName": "Ahmed",
                  "lastName": "Jude",
                  "email": "ahmed@mail.com",
                  "password": "password",
                  "gender": "male",
                  "mobile": "079445322",
                  "address": "34 Fito",
                  "department": "sales",
                  "role": "ceo",
                  "type": "user",
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z"
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Insufficient privileges to create account.",
            }

+ Response 422 (application/json)

  + Body

            {
              "status": "error",
              "error": "Bad data",
            }

## /auth/signin

### Signin user [POST]
+ Request (application/json)
  + Body

            {
              "email": "ahmed@mail.com",
              "password": "password",
            }

+ Response 200 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "token": "tfdfhdjfyreu68rehnfdjhfdjkfhcxcxh4545jfhd",
                  "id": "dcc00a10-06e2-11ea-8f0e-9168c8a7677c",
                  "username": "ahm",
                  "firstName": "Ahmed",
                  "lastName": "Jude",
                  "email": "ahmed@mail.com",
                  "password": "password",
                  "gender": "male",
                  "mobile": "079445322",
                  "address": "34 Fito",
                  "department": "sales",
                  "role": "ceo",
                  "type": "user",
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z"
              },
            }

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "error": "Invalid authentication credentials.",
            }

+ Response 404 (application/json)

  + Body

            {
              "status": "error",
              "error": "No user by that email found",
            }


# Group Comments Collection

## /comments/{id}/flag

### Post a flag [POST]

+ Parameters

  + id (string) - ID of the article (uuid/v1)

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

  + Body

            {
              "comment": "0957abd0-06d6-11ea-8d1e-d1fcfe25170f",
              "feedback": "I found this inappropriate...",
              "userId": "a4e45td0-064f-11ea-bda7-0f1cd9030e30"
            }

+ Response 201 (application/json)

  + Body

            {
              "status": "success",
              "data": {
                  "id": "1e8139f0-06ee-11ea-8f0e-9168c8a7677c",
                  "feedback": "I found this inappropriate...",
                  "user": {
                      "id": "a4e45td0-064f-11ea-bda7-0f1cd9030e30",
                      "username": "tommy",
                  },
                  "comment": {
                    "id": "671b2a30-06cc-11ea-8d1e-d1fcfe25170f",
                  },
                  "createdAt": "2015-08-05T08:40:51.620Z",
                  "updatedAt": "2015-08-05T08:40:51.620Z",
              },
            }

+ Response 401 (application/json)

  + Body

            {
                "status": "error",
                "error": "Not authorized",
            }

+ Response 422 (application/json)

  + Body

            {
                "status": "error",
                "error": "Bad data",
            }

+ Response 404 (application/json)

    + Body

            {
              "status": "error",
              "error": "No comment found by that identifier."
            }

### Delete A Comment [DELETE]

+ Request (application/json)

  + Headers

            Authorization: 'Bearer 4567890tyrehhr6775454h54h5hfdhdfhjdjrjr'

+ Response 204 (application/json)

+ Response 401 (application/json)

  + Body

            {
              "status": "error",
              "data": "Not authorized",
            }

+ Response 404 (application/json)

    + Body

            {
              "status": "error",
              "error": "No comment by that identifier."
            }