FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# teamwork

Teamwork is an **internal social network** for employees of an organization. The goal of this
application is to facilitate more interaction between colleagues and promote team bonding.

## Articles Collection [/articles]

### List All Articles [GET]

+ Response 200 (application/json)

        [
            {
                "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                "title": "Favourite programming language?",
                "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                "user": {
                    "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                    "username": "tommy",
                },
                "category": {
                    "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                    "name": "software",
                },
                "createdAt": "2015-08-05T08:40:51.620Z",
                "updatedAt": "2015-08-05T08:40:51.620Z",
                ]
            }
        ]

## Article [/articles/{id}]

+ Parameters
  + id (number) - ID of the article (uuid/v1)

### Get An Article [GET]

+ Response 200 (application/json)

        [
            {
                "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                "title": "Favourite programming language?",
                "text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                "user": {
                    "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                    "username": "tommy",
                },
                "category": {
                    "id": "a4e49bd0-064f-11ea-bda7-0f1cd9030e30",
                    "name": "software",
                },
                "createdAt": "2015-08-05T08:40:51.620Z",
                "updatedAt": "2015-08-05T08:40:51.620Z",
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
